/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "background":                "#0b1326",
        "surface":                   "#0b1326",
        "surface-dim":               "#0b1326",
        "surface-bright":            "#31394d",
        "surface-container-lowest":  "#060e20",
        "surface-container-low":     "#131b2e",
        "surface-container":         "#171f33",
        "surface-container-high":    "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant":           "#2d3449",
        "on-surface":                "#dae2fd",
        "on-surface-variant":        "#c7c4d7",
        "on-background":             "#dae2fd",
        "outline":                   "#908fa0",
        "outline-variant":           "#464554",
        "primary":                   "#c0c1ff",
        "on-primary":                "#1000a9",
        "primary-container":         "#8083ff",
        "on-primary-container":      "#0d0096",
        "primary-fixed":             "#e1e0ff",
        "primary-fixed-dim":         "#c0c1ff",
        "on-primary-fixed":          "#07006c",
        "on-primary-fixed-variant":  "#2f2ebe",
        "inverse-primary":           "#494bd6",
        "surface-tint":              "#c0c1ff",
        "secondary":                 "#4edea3",
        "on-secondary":              "#003824",
        "secondary-container":       "#00a572",
        "on-secondary-container":    "#00311f",
        "secondary-fixed":           "#6ffbbe",
        "secondary-fixed-dim":       "#4edea3",
        "on-secondary-fixed":        "#002113",
        "on-secondary-fixed-variant":"#005236",
        "tertiary":                  "#ffb95f",
        "on-tertiary":               "#472a00",
        "tertiary-container":        "#ca8100",
        "on-tertiary-container":     "#3e2400",
        "tertiary-fixed":            "#ffddb8",
        "tertiary-fixed-dim":        "#ffb95f",
        "on-tertiary-fixed":         "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "error":                     "#ffb4ab",
        "on-error":                  "#690005",
        "error-container":           "#93000a",
        "on-error-container":        "#ffdad6",
        "inverse-surface":           "#dae2fd",
        "inverse-on-surface":        "#283044",
      },
      borderRadius: {
        "sm":      "0.25rem",
        "DEFAULT": "0.5rem",
        "md":      "0.75rem",
        "lg":      "1.0rem",
        "xl":      "1.5rem",
        "full":    "9999px",
      },
      spacing: {
        "unit":              "4px",
        "container-margin":  "20px",
        "gutter":            "16px",
        "card-padding":      "24px",
        "stack-gap":         "12px",
      },
      fontFamily: {
        "display":            ["Montserrat", "sans-serif"],
        "display-lg":         ["Montserrat", "sans-serif"],
        "headline-lg":        ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "title-md":           ["Inter", "sans-serif"],
        "body-lg":            ["Inter", "sans-serif"],
        "label-caps":         ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg":         ["48px", { lineHeight:"56px", letterSpacing:"-0.02em", fontWeight:"800" }],
        "headline-lg":        ["32px", { lineHeight:"40px", fontWeight:"700" }],
        "headline-lg-mobile": ["24px", { lineHeight:"32px", fontWeight:"700" }],
        "title-md":           ["20px", { lineHeight:"28px", fontWeight:"600" }],
        "body-lg":            ["16px", { lineHeight:"24px", fontWeight:"400" }],
        "label-caps":         ["12px", { lineHeight:"16px", letterSpacing:"0.05em", fontWeight:"700" }],
      }
    },
  },
  plugins: [],
}
